### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by iAmKevinMcKee** [Geocodio/geocodio-library-php#4]
Any plan to support PHP 8?

**Comment by MiniCodeMonkey** [comment]
Thanks for requesting this. We’re working on it!

**Comment by devinfd** [comment]
Is there a timeline for this?

**Comment by devinfd** [comment]
Pull request: https://github.com/Geocodio/geocodio-library-php/pull/5

**Comment by MiniCodeMonkey** [comment]
Sorry! Hit a little snafu with Travis that delayed this. v1.4.0 with PHP 8 has been released now.
